In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

# 네이버

In [2]:
naver = pd.read_csv('naver_store1_3.csv')
naver.head()

,Unnamed: 0,user,store,time,rating,review,site
0,0,1,스타벅스 역삼아레나빌딩점,2021.04.09,3.5,친절해요~,naver
1,1,2,스타벅스 역삼아레나빌딩점,2021.04.06,5.0,역시 스벅,naver
2,2,4,스타벅스 역삼아레나빌딩점,2021.04.01,5.0,친절해요,naver
3,3,5,스타벅스 역삼아레나빌딩점,2021.03.27,5.0,넓고 깻끗해서좋아요,naver
4,4,6,스타벅스 역삼아레나빌딩점,2021.03.24,5.0,쾌적해요 집근처 스벅 중 최애,naver

## 결측값 처리

In [3]:
naver.isnull().sum()

Unnamed: 0      0
user            0
store           0
time            0
rating          0
review        540
site            0
dtype: int64

In [4]:
naver = naver.dropna()
naver

,Unnamed: 0,user,store,time,rating,review,site
0,0,1,스타벅스 역삼아레나빌딩점,2021.04.09,3.5,친절해요~,naver
1,1,2,스타벅스 역삼아레나빌딩점,2021.04.06,5.0,역시 스벅,naver
2,2,4,스타벅스 역삼아레나빌딩점,2021.04.01,5.0,친절해요,naver
3,3,5,스타벅스 역삼아레나빌딩점,2021.03.27,5.0,넓고 깻끗해서좋아요,naver
4,4,6,스타벅스 역삼아레나빌딩점,2021.03.24,5.0,쾌적해요 집근처 스벅 중 최애,naver
...,...,...,...,...,...,...,...
123525,3975,104,스타벅스 중화역점,2020.12.25,5.0,중화동에 스벅이 생기다니!,naver
123526,3976,126,스타벅스 중화역점,2020.12.23,5.0,친절해요~~,naver
123527,3977,130,스타벅스 중화역점,2020.12.23,4.0,주차비가 사악함,naver
123528,3978,131,스타벅스 중화역점,2020.12.23,4.0,커피벅스 드디어 중화에 떴다!,naver
123529,3979,132,스타벅스 중화역점,2020.12.22,4.0,"오픈한지 얼마 안되서 깔끔하고 넓고 친절하고, 커피 맛있음",naver

## DB를 위한 SiteID column(SiteDF의 PK) 생성 및 필요없는 column 제거

In [5]:
naver['SiteID'] = 1
naver = naver.drop(['site', 'Unnamed: 0', 'user'], axis=1)
naver

,store,time,rating,review,SiteID
0,스타벅스 역삼아레나빌딩점,2021.04.09,3.5,친절해요~,1
1,스타벅스 역삼아레나빌딩점,2021.04.06,5.0,역시 스벅,1
2,스타벅스 역삼아레나빌딩점,2021.04.01,5.0,친절해요,1
3,스타벅스 역삼아레나빌딩점,2021.03.27,5.0,넓고 깻끗해서좋아요,1
4,스타벅스 역삼아레나빌딩점,2021.03.24,5.0,쾌적해요 집근처 스벅 중 최애,1
...,...,...,...,...,...
123525,스타벅스 중화역점,2020.12.25,5.0,중화동에 스벅이 생기다니!,1
123526,스타벅스 중화역점,2020.12.23,5.0,친절해요~~,1
123527,스타벅스 중화역점,2020.12.23,4.0,주차비가 사악함,1
123528,스타벅스 중화역점,2020.12.23,4.0,커피벅스 드디어 중화에 떴다!,1
123529,스타벅스 중화역점,2020.12.22,4.0,"오픈한지 얼마 안되서 깔끔하고 넓고 친절하고, 커피 맛있음",1

In [6]:
naver.to_csv('./naver0412.csv')

## 카카오

In [7]:
kakao = pd.read_csv('kakao_reviews_total.csv')
kakao.head()

,iter_num,store,time,rating,review
0,0,스타벅스 강남R점,2021.03.24.,5.0,최고예요
1,1,스타벅스 강남R점,2021.03.20.,1.0,"리져브 주문 창구가 아닌, 일반 주문 창구에서 주문하는데...원두 2가지 중 선택할..."
2,2,스타벅스 강남R점,2021.02.03.,5.0,최고예요
3,3,스타벅스 강남R점,2020.11.14.,5.0,최고예요
4,4,스타벅스 강남R점,2020.11.12.,5.0,Great

## 결측값 처리

In [8]:
kakao.isnull().sum()

iter_num     13
store       357
time        357
rating      357
review      357
dtype: int64

In [9]:
kakao = kakao.dropna()
kakao

,iter_num,store,time,rating,review
0,0,스타벅스 강남R점,2021.03.24.,5.0,최고예요
1,1,스타벅스 강남R점,2021.03.20.,1.0,"리져브 주문 창구가 아닌, 일반 주문 창구에서 주문하는데...원두 2가지 중 선택할..."
2,2,스타벅스 강남R점,2021.02.03.,5.0,최고예요
3,3,스타벅스 강남R점,2020.11.14.,5.0,최고예요
4,4,스타벅스 강남R점,2020.11.12.,5.0,Great
...,...,...,...,...,...
6605,2,스타벅스 마리오아울렛점,2018.02.19.,3.0,보통이에요
6606,3,스타벅스 마리오아울렛점,2017.04.18.,3.0,보통이에요
6607,4,스타벅스 마리오아울렛점,2017.02.06.,4.0,좋아요
6610,0,스타벅스 대치삼성프라자점,2021.01.24.,1.0,아리수 수도물이 싫어서 아메리카노에 물은 빼고 에스프레소만 달라고 하는데 지침상 안...
6611,1,스타벅스 대치삼성프라자점,2020.10.09.,5.0,핸펀 사러가서 스벅 한잔 좋네요.

## DB를 위한 SiteID column(SiteDF의 PK) 생성 및 필요없는 column 제거

In [10]:
kakao['SiteID'] = 2
kakao = kakao.drop(['iter_num'], axis=1)
kakao

,store,time,rating,review,SiteID
0,스타벅스 강남R점,2021.03.24.,5.0,최고예요,2
1,스타벅스 강남R점,2021.03.20.,1.0,"리져브 주문 창구가 아닌, 일반 주문 창구에서 주문하는데...원두 2가지 중 선택할...",2
2,스타벅스 강남R점,2021.02.03.,5.0,최고예요,2
3,스타벅스 강남R점,2020.11.14.,5.0,최고예요,2
4,스타벅스 강남R점,2020.11.12.,5.0,Great,2
...,...,...,...,...,...
6605,스타벅스 마리오아울렛점,2018.02.19.,3.0,보통이에요,2
6606,스타벅스 마리오아울렛점,2017.04.18.,3.0,보통이에요,2
6607,스타벅스 마리오아울렛점,2017.02.06.,4.0,좋아요,2
6610,스타벅스 대치삼성프라자점,2021.01.24.,1.0,아리수 수도물이 싫어서 아메리카노에 물은 빼고 에스프레소만 달라고 하는데 지침상 안...,2
6611,스타벅스 대치삼성프라자점,2020.10.09.,5.0,핸펀 사러가서 스벅 한잔 좋네요.,2

In [11]:
kakao.to_csv('kakao0412.csv')

# google

# MangoPlate

In [12]:
mango = pd.read_csv('mango_reviews.csv').dropna() # 결측값 1개
mango['SiteID'] = 4
mango

,store,time,rating,review,SiteID
0,스타벅스 서강대프라자점,2019-10-20,3,드디어 주변에만 생기던 스벅이 서강대 교내에도 들어왔습니다! 동네 분들도 생각보다 ...,4
1,스타벅스 종로관철점,2021-01-27,5,이번 새로운 시즌메뉴 더블 에스프레소 크림라떼 존맛탱ㅜㅜ 바닐라 라떼랑 비스무리한데...,4
2,스타벅스 종로관철점,2018-09-22,3,요거 타르트 맛이쓔,4
3,스타벅스 등촌역점,2019-03-07,5,발렌타인 프로모션 음료 (화이트초콜릿 어쩌구였음)를 마셨는데 너무 달달하고 맛있었다...,4
4,스타벅스 선정릉역점,2020-03-26,5,트러플머쉬룸 스프!!! 다음번엔 두그릇먹어야겠다.,4
...,...,...,...,...,...
322,스타벅스 외대점,2015-12-13,5,오랜만에 와봤더니 매장 리뉴얼했네요. 예전에는 테이블 디자인 제각각이고 인테리어가 ...,4
323,스타벅스 외대점,2014-09-21,3,면적대비 좌석수가 많음에도 불구하고 항상 북적입니다. 주로 공부하는 분들이 많이 찾...,4
324,스타벅스 외대점,2014-07-13,5,맛있다. 좁다. 항상 사람이 많다. 일찍 문을 닫는다.,4
325,스타벅스 서초이화빌딩점,2019-12-29,3,일요일이라 서초역 근처에 온 길에 들러 본 스타벅스 서초역이화빌딩점. 비교적 새 ...,4
326,스타벅스 서초이화빌딩점,2018-11-04,5,몇 달 전에 동네에 새로 오픈한 스타벅스! 일요일 점심에 갔는데도 사람이 적었어요~...,4

In [13]:
mango.to_csv('mango0412.csv')

# Site

In [14]:
Site = pd.read_csv('Site_DF.csv')
Site['ReviewTotal'][0] = naver.review.count()
Site['ReviewTotal'][1] = kakao.review.count()
# Site['ReviewTotal'][2] = google.review.count()
Site['ReviewTotal'][3] = mango.review.count()
Site

   SiteID    SiteName  ReviewTotal
0       1       Naver     122990.0
1       2       Kakao       6255.0
2       3      Google          NaN
3       4  MangoPlate        326.0

In [15]:
Site.to_csv('site0412.csv')

# Stores

In [16]:
# store_info_DF
stores = pd.read_csv('starbucks_stores_info.csv')
stores

,store,address,latitude,longitude,isReserve
0,스타벅스 역삼아레나빌딩점,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069,general
1,스타벅스 논현역사거리점,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223,general
2,스타벅스 신사역성일빌딩점,서울특별시 강남구 강남대로 584 (논현동),37.514132,127.020563,general
3,스타벅스 국기원사거리점,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495,general
4,스타벅스 스탈릿대치R점,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583,reserve
...,...,...,...,...,...
536,스타벅스 사가정역점,서울특별시 중랑구 면목로 310,37.579594,127.087966,general
537,스타벅스 상봉역점,"서울특별시 중랑구 망우로 307, ,3,4번지 (상봉동)",37.596890,127.086470,general
538,스타벅스 묵동이마트점,"서울특별시 중랑구 동일로 932 (묵동, 묵동자이아파트) (묵동이마트 B1층)",37.613433,127.077484,general
539,스타벅스 묵동점,서울특별시 중랑구 동일로 952,37.615368,127.076633,general
540,스타벅스 중화역점,"서울특별시 중랑구 봉화산로 35 1,2층",37.601709,127.078411,general

In [17]:
reviewCount = naver.groupby('store').count().reset_index()[['store', 'review']]
reviewCount

              store  review
0        스타벅스 GS타워점     275
1    스타벅스 SSG마켓도곡R점     288
2      스타벅스 W-Mall점     428
3        스타벅스 가로수길점     294
4      스타벅스 가산그레이트점     338
..              ...     ...
310     스타벅스 황학사거리점     339
311      스타벅스 황학캐슬점     331
312    스타벅스 회기역사거리점     438
313       스타벅스 회현역점     180
314    스타벅스 효창공원앞역점     220

[315 rows x 2 columns]

In [24]:
storesInfo = pd.merge(stores, reviewCount, on='store', how='left')
storesInfo

,store,address,latitude,longitude,isReserve,review
0,스타벅스 역삼아레나빌딩점,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069,general,262.0
1,스타벅스 논현역사거리점,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223,general,384.0
2,스타벅스 신사역성일빌딩점,서울특별시 강남구 강남대로 584 (논현동),37.514132,127.020563,general,333.0
3,스타벅스 국기원사거리점,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495,general,341.0
4,스타벅스 스탈릿대치R점,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583,reserve,258.0
...,...,...,...,...,...,...
536,스타벅스 사가정역점,서울특별시 중랑구 면목로 310,37.579594,127.087966,general,655.0
537,스타벅스 상봉역점,"서울특별시 중랑구 망우로 307, ,3,4번지 (상봉동)",37.596890,127.086470,general,632.0
538,스타벅스 묵동이마트점,"서울특별시 중랑구 동일로 932 (묵동, 묵동자이아파트) (묵동이마트 B1층)",37.613433,127.077484,general,396.0
539,스타벅스 묵동점,서울특별시 중랑구 동일로 952,37.615368,127.076633,general,210.0
540,스타벅스 중화역점,"서울특별시 중랑구 봉화산로 35 1,2층",37.601709,127.078411,general,98.0

In [25]:
storesInfo.to_csv('stores0412.csv')

# 통합 리뷰 dataframe

In [22]:
reviews_merged = pd.concat([naver,kakao,mango],axis=0)
reviews_merged.to_csv('./reviews_merged.csv')

In [23]:
reviews_merged

,store,time,rating,review,SiteID
0,스타벅스 역삼아레나빌딩점,2021.04.09,3.5,친절해요~,1
1,스타벅스 역삼아레나빌딩점,2021.04.06,5.0,역시 스벅,1
2,스타벅스 역삼아레나빌딩점,2021.04.01,5.0,친절해요,1
3,스타벅스 역삼아레나빌딩점,2021.03.27,5.0,넓고 깻끗해서좋아요,1
4,스타벅스 역삼아레나빌딩점,2021.03.24,5.0,쾌적해요 집근처 스벅 중 최애,1
...,...,...,...,...,...
322,스타벅스 외대점,2015-12-13,5.0,오랜만에 와봤더니 매장 리뉴얼했네요. 예전에는 테이블 디자인 제각각이고 인테리어가 ...,4
323,스타벅스 외대점,2014-09-21,3.0,면적대비 좌석수가 많음에도 불구하고 항상 북적입니다. 주로 공부하는 분들이 많이 찾...,4
324,스타벅스 외대점,2014-07-13,5.0,맛있다. 좁다. 항상 사람이 많다. 일찍 문을 닫는다.,4
325,스타벅스 서초이화빌딩점,2019-12-29,3.0,일요일이라 서초역 근처에 온 길에 들러 본 스타벅스 서초역이화빌딩점. 비교적 새 ...,4
326,스타벅스 서초이화빌딩점,2018-11-04,5.0,몇 달 전에 동네에 새로 오픈한 스타벅스! 일요일 점심에 갔는데도 사람이 적었어요~...,4