In [1]:
import pandas as pd
kakao_reviews = pd.read_csv('./dataset/kakao_reviews_total.csv')
kakao_reviews

,iter_num,store,time,rating,review
0,0,스타벅스 강남R점,2021.03.24.,5.0,최고예요
1,1,스타벅스 강남R점,2021.03.20.,1.0,"리져브 주문 창구가 아닌, 일반 주문 창구에서 주문하는데...원두 2가지 중 선택할..."
2,2,스타벅스 강남R점,2021.02.03.,5.0,최고예요
3,3,스타벅스 강남R점,2020.11.14.,5.0,최고예요
4,4,스타벅스 강남R점,2020.11.12.,5.0,Great
...,...,...,...,...,...
6607,4,스타벅스 마리오아울렛점,2017.02.06.,4.0,좋아요
6608,이름설정ㅋㅋㅋㅋㅋㅋㅋㅋ ㅋㅋㅋㅋㅋㅋ젤우껴따ㅋㅋㅋㅋ 끝끝내 폰업뎃 완료!,NaN,NaN,NaN,NaN
6609,내가 갔던 스벅중에 젤 좋아하는곳 비교적 조용하고 중앙을 제외한 나머지부분이 천장이...,NaN,NaN,NaN,NaN
6610,0,스타벅스 대치삼성프라자점,2021.01.24.,1.0,아리수 수도물이 싫어서 아메리카노에 물은 빼고 에스프레소만 달라고 하는데 지침상 안...
6611,1,스타벅스 대치삼성프라자점,2020.10.09.,5.0,핸펀 사러가서 스벅 한잔 좋네요.

In [2]:
kakao_reviews.dropna(axis=0, inplace=True)
kakao_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6255 entries, 0 to 6611
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   iter_num  6255 non-null   object
 1   store     6255 non-null   object
 2   time      6255 non-null   object
 3   rating    6255 non-null   float64
 4   review    6255 non-null   object
dtypes: float64(1), object(4)
memory usage: 293.2+ KB

In [3]:
naver_reviews = pd.read_csv('./dataset/naver_store1_3.csv')
naver_reviews

,Unnamed: 0,user,store,time,rating,review,site
0,0,1,스타벅스 역삼아레나빌딩점,2021.04.09,3.5,친절해요~,naver
1,1,2,스타벅스 역삼아레나빌딩점,2021.04.06,5.0,역시 스벅,naver
2,2,4,스타벅스 역삼아레나빌딩점,2021.04.01,5.0,친절해요,naver
3,3,5,스타벅스 역삼아레나빌딩점,2021.03.27,5.0,넓고 깻끗해서좋아요,naver
4,4,6,스타벅스 역삼아레나빌딩점,2021.03.24,5.0,쾌적해요 집근처 스벅 중 최애,naver
...,...,...,...,...,...,...,...
123525,3975,104,스타벅스 중화역점,2020.12.25,5.0,중화동에 스벅이 생기다니!,naver
123526,3976,126,스타벅스 중화역점,2020.12.23,5.0,친절해요~~,naver
123527,3977,130,스타벅스 중화역점,2020.12.23,4.0,주차비가 사악함,naver
123528,3978,131,스타벅스 중화역점,2020.12.23,4.0,커피벅스 드디어 중화에 떴다!,naver
123529,3979,132,스타벅스 중화역점,2020.12.22,4.0,"오픈한지 얼마 안되서 깔끔하고 넓고 친절하고, 커피 맛있음",naver

In [4]:
naver_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123530 entries, 0 to 123529
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  123530 non-null  int64
 1   user        123530 non-null  int64
 2   store       123530 non-null  object
 3   time        123530 non-null  object
 4   rating      123530 non-null  float64
 5   review      122990 non-null  object
 6   site        123530 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 6.6+ MB

In [5]:
naver_reviews.dropna(axis=0, inplace=True)
naver_reviews.drop('Unnamed: 0', axis = 1, inplace = True)
naver_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 122990 entries, 0 to 123529
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   user    122990 non-null  int64
 1   store   122990 non-null  object
 2   time    122990 non-null  object
 3   rating  122990 non-null  float64
 4   review  122990 non-null  object
 5   site    122990 non-null  object
dtypes: float64(1), int64(1), object(4)
memory usage: 6.6+ MB

In [6]:
mango_reviews = pd.read_csv('./dataset/mango_reviews.csv')
mango_reviews

,store,time,rating,review
0,스타벅스 서강대프라자점,2019-10-20,3,드디어 주변에만 생기던 스벅이 서강대 교내에도 들어왔습니다! 동네 분들도 생각보다 ...
1,스타벅스 종로관철점,2021-01-27,5,이번 새로운 시즌메뉴 더블 에스프레소 크림라떼 존맛탱ㅜㅜ 바닐라 라떼랑 비스무리한데...
2,스타벅스 종로관철점,2018-09-22,3,요거 타르트 맛이쓔
3,스타벅스 등촌역점,2019-03-07,5,발렌타인 프로모션 음료 (화이트초콜릿 어쩌구였음)를 마셨는데 너무 달달하고 맛있었다...
4,스타벅스 선정릉역점,2020-03-26,5,트러플머쉬룸 스프!!! 다음번엔 두그릇먹어야겠다.
...,...,...,...,...
322,스타벅스 외대점,2015-12-13,5,오랜만에 와봤더니 매장 리뉴얼했네요. 예전에는 테이블 디자인 제각각이고 인테리어가 ...
323,스타벅스 외대점,2014-09-21,3,면적대비 좌석수가 많음에도 불구하고 항상 북적입니다. 주로 공부하는 분들이 많이 찾...
324,스타벅스 외대점,2014-07-13,5,맛있다. 좁다. 항상 사람이 많다. 일찍 문을 닫는다.
325,스타벅스 서초이화빌딩점,2019-12-29,3,일요일이라 서초역 근처에 온 길에 들러 본 스타벅스 서초역이화빌딩점. 비교적 새 ...
326,스타벅스 서초이화빌딩점,2018-11-04,5,몇 달 전에 동네에 새로 오픈한 스타벅스! 일요일 점심에 갔는데도 사람이 적었어요~...

In [10]:
mango_reviews[mango_reviews['review'].duplicated() == True]

Empty DataFrame
Columns: [store, time, rating, review]
Index: []

In [11]:
kakao_reviews[kakao_reviews['review'].duplicated() == True]

     iter_num         store         time  rating review
2           2     스타벅스 강남R점  2021.02.03.     5.0   최고예요
3           3     스타벅스 강남R점  2020.11.14.     5.0   최고예요
6           1     스타벅스 강남R점  2020.09.28.     5.0   최고예요
7           2     스타벅스 강남R점  2020.08.22.     5.0   최고예요
10          0     스타벅스 강남R점  2020.07.17.     4.0    좋아요
...       ...           ...          ...     ...    ...
6598        3   스타벅스 묵동이마트점  2017.05.19.     5.0   최고예요
6600        1    스타벅스 상일동역점  2021.03.06.     4.0    좋아요
6605        2  스타벅스 마리오아울렛점  2018.02.19.     3.0  보통이에요
6606        3  스타벅스 마리오아울렛점  2017.04.18.     3.0  보통이에요
6607        4  스타벅스 마리오아울렛점  2017.02.06.     4.0    좋아요

[2384 rows x 5 columns]

In [12]:
naver_reviews[naver_reviews['review'].duplicated() == True]

        user          store        time  rating       review   site
10        12  스타벅스 역삼아레나빌딩점  2021.03.19     4.0          좋아요  naver
12        14  스타벅스 역삼아레나빌딩점  2021.03.10     4.0          좋아요  naver
13        15  스타벅스 역삼아레나빌딩점  2021.03.10     4.0          좋아요  naver
14        16  스타벅스 역삼아레나빌딩점  2021.03.10     4.0          좋아요  naver
18        20  스타벅스 역삼아레나빌딩점  2021.03.03     4.0          좋아요  naver
...      ...            ...         ...     ...          ...    ...
123519    95      스타벅스 중화역점  2021.01.01     5.0  #스타벅스 #중화역점  naver
123521    97      스타벅스 중화역점  2020.12.31     5.0          좋아요  naver
123522    98      스타벅스 중화역점  2020.12.30     5.0         좋아요~  naver
123523    99      스타벅스 중화역점  2020.12.29     4.0          좋아요  naver
123526   126      스타벅스 중화역점  2020.12.23     5.0       친절해요~~  naver

[68068 rows x 6 columns]